# Permutations and Factorials - Lab

## Introduction

Before, we saw how the creation of a sample space is crucial in finding probabilities. The issue, however is that, when the sample space grows bigger, it is not straightforward to manually compute the size of sample sets anymore.

Luckily, probability theory provides us with several formulas that can help us out. One set of formulas is known as **permutations**. This lab will help you get a better understanding of permutations, and provide practice!

## Objectives

You will be able to:

* Mathematically derive how many permutations there are for large sets
* Calculate permutations of a subset
* Calculate permutations with repetition and replacement

## A Note on Factorials

In the last lesson, we talked about permutations in the context of a coverband creating a setlist. We wanted to calculate how many ways we can order 3 songs in their setlist. We can use factorials for that. For 3 songs, this boils down to

In [1]:
setlist = 3*2*1

Now, writing this out is not an issue when $n$ is small. What if $n$ grows though? Imagine there are 10 songs in the setlist

In [2]:
setlist = 10*9*8*7*6*5*4*3*2*1

You wouldn't want to repeat this for 25 songs...  Let's create a function for this!

What you'll do below is:

- create a function that takes one argument, $n$
- initialize `prod` as 1
- next, use `prod` in a `while` loop (what is the stopping criterion?)
- update $n$ so it decreases with value 1 each iteration. This way you essentially calculate $n*(n-1)*(n-2)*\ldots*(1)$

In [3]:
def factorial(n):
    prod = 1
    while n > 1:
        prod *= n
        n -= 1
    return prod

Now, test your function with n=20

In [4]:
factorial(20)

2432902008176640000

Just so you know, Python has a built-in function `factorial` in the  `math` library as well! Let's use our own function in this lab, but just use the `math` function once to check your previous answer!

In [5]:
import math 

math.factorial(20) == factorial(20)

True

## Some Practice on Permutations

Let's go back to the appointments exercise from the last lab. A teaching assistant is holding office hours so students can make appointments. She has 6 appointments scheduled today, 3 by male students and 3 by female students. How many ways are there to order the appointments, based on gender of the students? Just to clarify, we're looking for size of the sample space that lists possible orders like this:

FMFMFM <br />
MMMFFF <br />
FMFMMF <br />
...


From what you learned in the permutations lecture, you now have a more structured way of getting to the whole sample space! 

Hint: a permutation with repetition is needed here, with formula $\dfrac{n!}{n_1!n_2!\ldots n_k!}$. Think carefully of what needs to go in the denominator and the numerator respectively. 

In [6]:
app_num = factorial(6)
app_num

720

In [7]:
app_denom = factorial(3)*factorial(3)
app_denom

36

In [8]:
app_total = app_num/app_denom
app_total

20.0

## Permutations: Hack a Phone

You misplaced your iPhone and are afraid it was stolen. Luckily, your iPhone needs a 4-digit code in order to get in. Imagine that a potential thief can do five attempts at getting the code right before the phone is permanently locked, how big is the chance the thief unlocks the phone?

Think about the sample space and the event space separately. You'll use the formula $P(E) = \dfrac{|E|}{|S|}$ here.

So what should go in the denominator?

In [9]:
denom_phone = 10**4
denom_phone

10000

And the numerator?

In [10]:
numer_phone = 5
numer_phone

5

In [11]:
prob_unlock = numer_phone/denom_phone
prob_unlock

0.0005

Right before you lost your phone you ate a pretzel, and you are pretty sure a grease pattern was left on the four crucial digits of your screen. The four letters in your access code are 3,4,7 and 8, and you realize that this information can increase the thief's chances massively. Assuming the thief interprets the smudgemarks in an intelligent way, what are the chances that the phone will be unlocked successfully?

In [12]:
denom_phone_smudge = factorial(4) #or math.factorial(4)
denom_phone_smudge

24

In [13]:
numer_phone_smudge = 5
numer_phone_smudge

5

In [14]:
prob_unlock_smudge = numer_phone_smudge/denom_phone_smudge
prob_unlock_smudge

0.20833333333333334

Now, imagine you chose an iphone access code containing 3 different numbers, with numbers 2,7 and 8 (the code is still 4 digits). Now, the thief knows 1 number was reused (permutations with repetition!), but he doesn't know which one. what is the probability now that the phone will be unlocked successfully?

- For the denominator here, use a permutation with repetition, along with the fact that **you don't know which one is repeated**. Hint: you'll have to multiply your final "permutation with repetition"-result to account for that.
- For the numerator, use the numerator you used before: the number of trials the thief can try before the phone access is blocked.


In [15]:
denom_phone_smudge_2 = (factorial(4)/factorial(2))*3 #or use math.factorial(4)
denom_phone_smudge_2

36.0

In [16]:
numer_phone_smudge_2 = numer_phone_smudge 
numer_phone_smudge_2

5

In [17]:
prob_unlock_smudge_2 = numer_phone_smudge/denom_phone_smudge_2
prob_unlock_smudge_2

0.1388888888888889

## Permutations to Find the Sample and Event Space

What are the odds of throwing a "full house" when throwing 5 dice?  Recall, a full house means that you'd throw a three of a certain number along with a pair of a different number.

###  a) Sample space

First, calculate the sample space. Recall that replacement is possible here.

In [18]:
# each die has value 1 - 6 and we roll 5 times, so
import numpy as np

sample_space_fh = np.array([(d1, d2, d3, d4, d5) for d1 in range(1, 7) for d2 in range(1,7) for d3 in range(1,7) for d4 in range(1,7) for d5 in range(1,7)])
sample_space_fh

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 2],
       [1, 1, 1, 1, 3],
       ...,
       [6, 6, 6, 6, 4],
       [6, 6, 6, 6, 5],
       [6, 6, 6, 6, 6]])

In [19]:
size_sample_space = len(sample_space_fh)
size_sample_space

7776

In [20]:
# note that we don't actually have to build the sample space, given that the initial logic dictates that size_sample_space==6^5
#   let's confirm
size_sample_space == 6**5

True

### b) Event space

Next, calculate the event space. The best way to think of the event space here is to split it up in 2 parts:
- first, try to constrain your problem to a more specific problem, let's say, how many ways can we throw a full house if we have a pair of 4s and three 6s?
- next, extend your problem by asking yourself how many *different* full houses are possible.
- multiply the two!

In [21]:
# let's deal with pairs which will constitute a satsifying full house
#   e.g. {1, 1}, {2, 2}, ... {6, 6}, so...
#   there are 6 ways to so this
#
#   furthermore, for each pair (2-element set), there are corresponding 3-element sets which will constitute a full house
#      for example:
#      {1, 1}: {2, 2, 2}, {3, 3, 3}, ..., {6, 6, 6}   (there are 5 such 3-element sets)
#      {2, 2}: {1, 1, 1}, {3, 3, 3}, ..., {6, 6, 6}   (again, there are 5 such 3-element sets)
#      .
#      .
#      .
#      {6, 6}: {1, 1, 1}, {2, 2, 2}, ..., {5, 5, 5}   (also, there are 5 such 3-element sets)
#
#   i.e. for each of the 6 satisfying 2-element sets, there are 5 corresponding satisfying 3-element sets
#
#   thus, there are 6*5 couplings of satisfying 2-element sets and 3-element sets to get a full house
#
#   BUT, this says nothing about the ARRANGEMENT of the dice - we need to account for that somehow
#      for example for the satisfying coupling of:
#         {1,1}, {2,2,2}: we have the following arrangments:
#            [1,1,2,2,2], 
#            [1,2,1,2,2],
#            [1,2,2,1,2],
#            [1,2,2,2,1],
#            [2,1,1,2,2],
#            [2,1,2,1,2],
#            [2,1,2,2,1],
#            [2,2,1,1,2],
#            [2,2,1,2,1],
#            [2,2,2,1,1],
#
#   Thus, for each of the 6*5 couplings of satisfying 2-element sets and 3-element sets, there are 10 possible "arrangements".
#   Therefore, the total number of ways to get a full house are 6*5*10, or 300.
count_of_satisfying_2_element_sets = 6
count_of_satisfyinf_3_element_sets_for_each_2_element_set = 5
count_of_arrangements = 10
manually_derived_ways_to_get_fh = count_of_satisfying_2_element_sets * count_of_satisfyinf_3_element_sets_for_each_2_element_set * count_of_arrangements
manually_derived_ways_to_get_fh

300

Then the event space is

In [22]:
# one way to build the event space is simply to convert each item in the sample space to sets
#   since, by definition, sets do not admit duplicate items,
#      any set-converted-item from the sample space that has two distinct elements,
#         where each of those set-converted-items occurs 2 or 3 times in the original sample space item
#      will result from a sample space item that has satisfying 2-element and 3-element sets
event_space_fh = np.array(
    list(
        filter(
            lambda roll: len(set(roll))==2 and (list(roll).count(roll[0])==2 or list(roll).count(roll[0])==3)
            , list(sample_space_fh)
        )
    )
)

# output some results to show this...
print(event_space_fh[0:5])
print(event_space_fh[5:10])

[[1 1 1 2 2]
 [1 1 1 3 3]
 [1 1 1 4 4]
 [1 1 1 5 5]
 [1 1 1 6 6]]
[[1 1 2 1 2]
 [1 1 2 2 1]
 [1 1 2 2 2]
 [1 1 3 1 3]
 [1 1 3 3 1]]


In [23]:
len(event_space_fh)

300

In [29]:
# now let's use combinatorics
#   binomial coefficients tells how how many ways we can "arrange" 5 things taken 3 (or 2) at a time
#      this is also known as "n choose r" and a function to compute it is given below

def nCr(n, r):
    return int(factorial(n)/(factorial(r)*factorial(n-r)))

In [30]:
# since nCr gives us the number of ways to arrange 5 things taken 3 at a time, we have 
computed_ways_to_get_fh = count_of_satisfying_2_element_sets \
    * count_of_satisfyinf_3_element_sets_for_each_2_element_set \
    * nCr(5, 3)
computed_ways_to_get_fh

300

### c) Probability of full house

In [26]:
prob_fh = computed_ways_to_get_fh/size_sample_space
prob_fh

0.038580246913580245

## Summary

Great job! You got quite some practice with permutations and factorials, and were even able to use it to calculate probability. Now, we'll move over to another concept in combinatorics: combinations.